In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import confusion_matrix, classification_report, precision_score
from sklearn import preprocessing
from sklearn import neighbors

In [73]:
df=pd.read_csv("C:\\Users\\soura\\Documents\\DS_ML_assignments/CatsAndDogs_v2.csv")
df

Height  Weight  Length  FurLength  PawSize  EarShape  Animal
0       25       4      30          0        0         0       0
1       32       6      38          1        1         2       0
2       38       8      45          2        2         1       1
3       28       5      35          0        0         0       0
4       35       7      42          1        1         2       1
5       30       6      36          0        0         0       0
6       31       5      37          0        0         0       0
7       34       7      41          1        1         2       1
8       29       4      35          0        0         0       0
9       32       6      38          1        1         1       2
10      36       8      43          2        2         1       1
11      27       5      33          0        0         0       0
12      33       6      40          1        1         2       1
13      26       4      32          0        0         0       0
14      35       7      42          1        1         2       0
15      30       5      36          0        0         0       1
16      28       4      34          0        0         0       0
17      31       6      37          0        0         0       0
18      34       7      41          1        1         2       1
19      29       5      35          0        0         0       0
20      32       6      38          1        1         1       2
21      36       8      43          2        2         1       1
22      27       5      33          0        0         0       0
23      33       6      40          1        1         2       1
24      26       4      32          0        0         0       0
25      35       7      42          1        1         2       0
26      30      10      38          1        1         2       1
27      32       9      40          1        1         2       0
28      35      11      43          2        2         1       1
29      28       9      35          1        1         2       0
30      31      10      37          1        1         2       1
31      38      12      45          2        2         1       1
32      40      15      50          2        2         1       1
33      35      10      42          1        1         2       1
34      32       9      38          1        1         2       0
35      36      11      44          2        2         1       1
36      28       8      35          1        1         2       0
37      31       9      37          1        1         2       1
38      34      10      41          1        1         2       1
39      29       8      35          1        1         2       0
40      60      30     100          2        2         1       1
41      55      25      90          2        2         1       1
42      45      18      70          1        1         1       1
43      65      35     110          2        2         1       1
44      50      20      80          2        2         1       1
45      42      15      65          1        1         1       1
46      38      12      55          1        1         1       1
47      30       6      36          0        0         0       0
48      35       7      42          1        1         2       1

In [75]:
X=df.drop("Animal", axis=1)
y=df.Animal

In [77]:
X

Height  Weight  Length  FurLength  PawSize  EarShape
0       25       4      30          0        0         0
1       32       6      38          1        1         2
2       38       8      45          2        2         1
3       28       5      35          0        0         0
4       35       7      42          1        1         2
5       30       6      36          0        0         0
6       31       5      37          0        0         0
7       34       7      41          1        1         2
8       29       4      35          0        0         0
9       32       6      38          1        1         1
10      36       8      43          2        2         1
11      27       5      33          0        0         0
12      33       6      40          1        1         2
13      26       4      32          0        0         0
14      35       7      42          1        1         2
15      30       5      36          0        0         0
16      28       4      34          0        0         0
17      31       6      37          0        0         0
18      34       7      41          1        1         2
19      29       5      35          0        0         0
20      32       6      38          1        1         1
21      36       8      43          2        2         1
22      27       5      33          0        0         0
23      33       6      40          1        1         2
24      26       4      32          0        0         0
25      35       7      42          1        1         2
26      30      10      38          1        1         2
27      32       9      40          1        1         2
28      35      11      43          2        2         1
29      28       9      35          1        1         2
30      31      10      37          1        1         2
31      38      12      45          2        2         1
32      40      15      50          2        2         1
33      35      10      42          1        1         2
34      32       9      38          1        1         2
35      36      11      44          2        2         1
36      28       8      35          1        1         2
37      31       9      37          1        1         2
38      34      10      41          1        1         2
39      29       8      35          1        1         2
40      60      30     100          2        2         1
41      55      25      90          2        2         1
42      45      18      70          1        1         1
43      65      35     110          2        2         1
44      50      20      80          2        2         1
45      42      15      65          1        1         1
46      38      12      55          1        1         1
47      30       6      36          0        0         0
48      35       7      42          1        1         2

In [79]:
y

0     0
1     0
2     1
3     0
4     1
5     0
6     0
7     1
8     0
9     2
10    1
11    0
12    1
13    0
14    0
15    1
16    0
17    0
18    1
19    0
20    2
21    1
22    0
23    1
24    0
25    0
26    1
27    0
28    1
29    0
30    1
31    1
32    1
33    1
34    0
35    1
36    0
37    1
38    1
39    0
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    0
48    1
Name: Animal, dtype: int64

In [81]:
from sklearn.model_selection import train_test_split
from sklearn import metrics as sm

In [83]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=15)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((39, 6), (10, 6), (39,), (10,))

In [85]:
knn = neighbors.KNeighborsClassifier()
pred = knn.fit(X_train, y_train).predict(X_test)
pred

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [87]:
print(confusion_matrix(y_test, pred).T)

[[3 2]
 [1 4]]


In [89]:
print(classification_report(y_test, pred, digits=2))

              precision    recall  f1-score   support

           0       0.60      0.75      0.67         4
           1       0.80      0.67      0.73         6

    accuracy                           0.70        10
   macro avg       0.70      0.71      0.70        10
weighted avg       0.72      0.70      0.70        10



In [91]:
knn = neighbors.KNeighborsClassifier(n_neighbors=3)
pred = knn.fit(X_train, y_train).predict(X_test)
pred

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [93]:
print(confusion_matrix(y_test, pred).T)
print(classification_report(y_test, pred, digits=2))

[[3 2]
 [1 4]]
              precision    recall  f1-score   support

           0       0.60      0.75      0.67         4
           1       0.80      0.67      0.73         6

    accuracy                           0.70        10
   macro avg       0.70      0.71      0.70        10
weighted avg       0.72      0.70      0.70        10

